

services:
  db-productos:
    image: postgres:16
    container_name: db-productos
    environment:
      POSTGRES_DB: productosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-productos
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db-productos
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
