spring.application.name=Producto

spring.datasource.url=jdbc:postgresql://localhost:5432/productosdb
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostrar SQLs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

